-- Drug interaction knowledge base — EXPANSION (Feature 2, 2026-06-25).
-- Adds ~955 clinically-grounded ingredient pairs generated from drug-class rules
-- (NSAID/anticoagulant/statin/serotonergic/QT/azole/macrolide/eye-drop hubs...).
-- Tokens are BASE generics verified to appear as substrings of the formulary's
-- drugs.LastName, so the CONTAINS match in DrugInteractionService fires correctly.
-- IMPORTANT: uses 'acetylsalicylic' (the real ASA naming) — the earlier 'aspirin'
-- rows did NOT match (formulary names aspirin "ACETYLSALICYLIC ACID").
-- Idempotent: INSERT IGNORE on UNIQUE(ingredient_a, ingredient_b); a<b alphabetical.

CREATE TABLE IF NOT EXISTS drug_interactions (
    id           INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    ingredient_a VARCHAR(190) NOT NULL,
    ingredient_b VARCHAR(190) NOT NULL,
    severity     ENUM('contraindicated','major','moderate','minor') NOT NULL DEFAULT 'moderate',
    description  VARCHAR(500) NOT NULL,
    source       VARCHAR(40)  NOT NULL DEFAULT 'curated',
    created_at   TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY uniq_pair (ingredient_a, ingredient_b),
    KEY idx_a (ingredient_a),
    KEY idx_b (ingredient_b)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT IGNORE INTO drug_interactions (ingredient_a, ingredient_b, severity, description) VALUES
('aceclofenac','acetylsalicylic','moderate','NSAID + antiplatelet — increased GI/bleeding risk.'),
('aceclofenac','alendronate','moderate','NSAID + bisphosphonate — additive GI/esophageal irritation.'),
('aceclofenac','apixaban','major','NSAID + anticoagulant — markedly increased bleeding risk.'),
('aceclofenac','betamethasone','moderate','NSAID + corticosteroid — additive GI ulcer/bleeding risk.'),
('aceclofenac','candesartan','moderate','NSAID reduces ACE/ARB effect and adds renal risk.'),
('aceclofenac','celecoxib','moderate','Two NSAIDs — additive GI ulcer / renal risk; avoid combining.'),
('aceclofenac','ciprofloxacin','minor','Quinolone + NSAID — slight seizure-threshold lowering.'),
('aceclofenac','clopidogrel','moderate','NSAID + antiplatelet — increased GI/bleeding risk.'),
('aceclofenac','dabigatran','major','NSAID + anticoagulant — markedly increased bleeding risk.'),
('aceclofenac','dexamethasone','moderate','NSAID + corticosteroid — additive GI ulcer/bleeding risk.'),
('aceclofenac','diclofenac','moderate','Two NSAIDs — additive GI ulcer / renal risk; avoid combining.'),
('aceclofenac','digoxin','moderate','NSAID may raise digoxin levels.'),
('aceclofenac','enalapril','moderate','NSAID reduces ACE/ARB effect and adds renal risk.'),
('aceclofenac','enoxaparin','major','NSAID + anticoagulant — markedly increased bleeding risk.'),
('aceclofenac','etoricoxib','moderate','Two NSAIDs — additive GI ulcer / renal risk; avoid combining.'),
('aceclofenac','furosemide','moderate','NSAID reduces diuretic effect; renal risk.'),
('aceclofenac','glibenclamide','minor','NSAID may enhance sulfonylurea hypoglycemia.'),
('aceclofenac','gliclazide','minor','NSAID may enhance sulfonylurea hypoglycemia.'),
('aceclofenac','glimepiride','minor','NSAID may enhance sulfonylurea hypoglycemia.'),
('aceclofenac','heparin','major','NSAID + anticoagulant — markedly increased bleeding risk.'),
('aceclofenac','hydrochlorothiazide','moderate','NSAID reduces diuretic effect; renal risk.'),
('aceclofenac','ibuprofen','moderate','Two NSAIDs — additive GI ulcer / renal risk; avoid combining.'),
('aceclofenac','indapamide','moderate','NSAID reduces diuretic effect; renal risk.'),
('aceclofenac','indomethacin','moderate','Two NSAIDs — additive GI ulcer / renal risk; avoid combining.'),
('aceclofenac','ketorolac','moderate','Two NSAIDs — additive GI ulcer / renal risk; avoid combining.'),
('aceclofenac','levofloxacin','minor','Quinolone + NSAID — slight seizure-threshold lowering.'),
('aceclofenac','lisinopril','moderate','NSAID reduces ACE/ARB effect and adds renal risk.'),
('aceclofenac','lithium','major','NSAID raises lithium levels — toxicity.'),
('aceclofenac','losartan','moderate','NSAID reduces ACE/ARB effect and adds renal risk.'),
('aceclofenac','mefenamic','moderate','Two NSAIDs — additive GI ulcer / renal risk; avoid combining.'),
('aceclofenac','meloxicam','moderate','Two NSAIDs — additive GI ulcer / renal risk; avoid combining.'),
('aceclofenac','methotrexate','major','NSAID raises methotrexate toxicity.'),
('aceclofenac','methylprednisolone','moderate','NSAID + corticosteroid — additive GI ulcer/bleeding risk.'),
('aceclofenac','moxifloxacin','minor','Quinolone + NSAID — slight seizure-threshold lowering.'),
('aceclofenac','naproxen','moderate','Two NSAIDs — additive GI ulcer / renal risk; avoid combining.'),
('aceclofenac','ofloxacin','minor','Quinolone + NSAID — slight seizure-threshold lowering.'),
('aceclofenac','piroxicam','moderate','Two NSAIDs — additive GI ulcer / renal risk; avoid combining.'),
('aceclofenac','prednisolone','moderate','NSAID + corticosteroid — additive GI ulcer/bleeding risk.'),
('aceclofenac','ramipril','moderate','NSAID reduces ACE/ARB effect and adds renal risk.'),
('aceclofenac','risedronate','moderate','NSAID + bisphosphonate — additive GI/esophageal irritation.'),
('aceclofenac','rivaroxaban','major','NSAID + anticoagulant — markedly increased bleeding risk.'),
('aceclofenac','spironolactone','moderate','NSAID + spironolactone — hyperkalemia / renal risk.'),
('aceclofenac','telmisartan','moderate','NSAID reduces ACE/ARB effect and adds renal risk.'),
('aceclofenac','valsartan','moderate','NSAID reduces ACE/ARB effect and adds renal risk.'),
('aceclofenac','warfarin','major','NSAID + anticoagulant — markedly increased bleeding risk.'),
('aceclofenac','zoledronic','moderate','NSAID + bisphosphonate — additive GI/esophageal irritation.'),
('acetazolamide','acetylsalicylic','major','Acetazolamide + high-dose salicylate — salicylate toxicity.'),
('acetazolamide','betamethasone','moderate','Acetazolamide + corticosteroid — additive hypokalemia.'),
('acetazolamide','dexamethasone','moderate','Acetazolamide + corticosteroid — additive hypokalemia.'),
('acetazolamide','furosemide','moderate','Acetazolamide + diuretic — additive hypokalemia.'),
('acetazolamide','hydrochlorothiazide','moderate','Acetazolamide + diuretic — additive hypokalemia.'),
('acetazolamide','indapamide','moderate','Acetazolamide + diuretic — additive hypokalemia.'),
('acetazolamide','methylprednisolone','moderate','Acetazolamide + corticosteroid — additive hypokalemia.'),
('acetazolamide','prednisolone','moderate','Acetazolamide + corticosteroid — additive hypokalemia.'),
('acetylsalicylic','apixaban','major','Antiplatelet + anticoagulant — increased bleeding risk.'),
('acetylsalicylic','betamethasone','moderate','Aspirin + corticosteroid — additive GI ulcer/bleeding risk.'),
('acetylsalicylic','celecoxib','moderate','NSAID + antiplatelet — increased GI/bleeding risk.'),
('acetylsalicylic','citalopram','moderate','SSRI/SNRI + antiplatelet — increased GI bleeding risk.'),
('acetylsalicylic','clopidogrel','moderate','Two antiplatelets — additive bleeding risk.'),
('acetylsalicylic','dabigatran','major','Antiplatelet + anticoagulant — increased bleeding risk.'),
('acetylsalicylic','dexamethasone','moderate','Aspirin + corticosteroid — additive GI ulcer/bleeding risk.'),
('acetylsalicylic','diclofenac','moderate','NSAID + antiplatelet — increased GI/bleeding risk.'),
('acetylsalicylic','duloxetine','moderate','SSRI/SNRI + antiplatelet — increased GI bleeding risk.'),
('acetylsalicylic','enoxaparin','major','Antiplatelet + anticoagulant — increased bleeding risk.'),
('acetylsalicylic','escitalopram','moderate','SSRI/SNRI + antiplatelet — increased GI bleeding risk.'),
('acetylsalicylic','etoricoxib','moderate','NSAID + antiplatelet — increased GI/bleeding risk.'),
('acetylsalicylic','fluoxetine','moderate','SSRI/SNRI + antiplatelet — increased GI bleeding risk.'),
('acetylsalicylic','fluvoxamine','moderate','SSRI/SNRI + antiplatelet — increased GI bleeding risk.'),
('acetylsalicylic','heparin','major','Antiplatelet + anticoagulant — increased bleeding risk.'),
('acetylsalicylic','ibuprofen','moderate','NSAID + antiplatelet — increased GI/bleeding risk.'),
('acetylsalicylic','indomethacin','moderate','NSAID + antiplatelet — increased GI/bleeding risk.'),
('acetylsalicylic','ketorolac','major','Ketorolac + antiplatelet — high GI/bleeding risk.'),
('acetylsalicylic','lithium','moderate','Salicylate may raise lithium levels.'),
('acetylsalicylic','mefenamic','moderate','NSAID + antiplatelet — increased GI/bleeding risk.'),
('acetylsalicylic','meloxicam','moderate','NSAID + antiplatelet — increased GI/bleeding risk.'),
('acetylsalicylic','methotrexate','major','Salicylate raises methotrexate toxicity.'),
('acetylsalicylic','methylprednisolone','moderate','Aspirin + corticosteroid — additive GI ulcer/bleeding risk.'),
('acetylsalicylic','naproxen','moderate','NSAID + antiplatelet — increased GI/bleeding risk.'),
('acetylsalicylic','paroxetine','moderate','SSRI/SNRI + antiplatelet — increased GI bleeding risk.'),
('acetylsalicylic','piroxicam','moderate','NSAID + antiplatelet — increased GI/bleeding risk.'),
('acetylsalicylic','prednisolone','moderate','Aspirin + corticosteroid — additive GI ulcer/bleeding risk.'),
('acetylsalicylic','rivaroxaban','major','Antiplatelet + anticoagulant — increased bleeding risk.'),
('acetylsalicylic','sertraline','moderate','SSRI/SNRI + antiplatelet — increased GI bleeding risk.'),
('acetylsalicylic','venlafaxine','moderate','SSRI/SNRI + antiplatelet — increased GI bleeding risk.'),
('acetylsalicylic','warfarin','major','Antiplatelet + anticoagulant — increased bleeding risk.'),
('alendronate','celecoxib','moderate','NSAID + bisphosphonate — additive GI/esophageal irritation.'),
('alendronate','diclofenac','moderate','NSAID + bisphosphonate — additive GI/esophageal irritation.'),
('alendronate','etoricoxib','moderate','NSAID + bisphosphonate — additive GI/esophageal irritation.'),
('alendronate','ibuprofen','moderate','NSAID + bisphosphonate — additive GI/esophageal irritation.'),
('alendronate','indomethacin','moderate','NSAID + bisphosphonate — additive GI/esophageal irritation.'),
('alendronate','ketorolac','moderate','NSAID + bisphosphonate — additive GI/esophageal irritation.'),
('alendronate','mefenamic','moderate','NSAID + bisphosphonate — additive GI/esophageal irritation.'),
('alendronate','meloxicam','moderate','NSAID + bisphosphonate — additive GI/esophageal irritation.'),
('alendronate','naproxen','moderate','NSAID + bisphosphonate — additive GI/esophageal irritation.'),
('alendronate','piroxicam','moderate','NSAID + bisphosphonate — additive GI/esophageal irritation.'),
('allopurinol','amoxicillin','minor','Allopurinol + aminopenicillin — increased rash risk.'),
('allopurinol','theophylline','major','Raises theophylline levels — toxicity.'),
('allopurinol','warfarin','moderate','Allopurinol may raise warfarin effect.'),
('amiodarone','atenolol','major','Beta-blocker + amiodarone — bradycardia / AV block.'),
('amiodarone','atorvastatin','major','Amiodarone raises statin levels — myopathy risk.'),
('amiodarone','betaxolol','moderate','Topical beta-blocker — additive bradycardia.'),
('amiodarone','bisoprolol','major','Beta-blocker + amiodarone — bradycardia / AV block.'),
('amiodarone','carvedilol','major','Beta-blocker + amiodarone — bradycardia / AV block.'),
('amiodarone','citalopram','major','Additive QT prolongation — torsades de pointes risk.'),
('amiodarone','clarithromycin','major','Additive QT prolongation — torsades de pointes risk.'),
('amiodarone','digoxin','major','Raises digoxin levels — toxicity.'),
('amiodarone','domperidone','major','Additive QT prolongation — torsades de pointes risk.'),
('amiodarone','escitalopram','major','Additive QT prolongation — torsades de pointes risk.'),
('amiodarone','haloperidol','major','Additive QT prolongation — torsades de pointes risk.'),
('amiodarone','metoprolol','major','Beta-blocker + amiodarone — bradycardia / AV block.'),
('amiodarone','moxifloxacin','major','Additive QT prolongation — torsades de pointes risk.'),
('amiodarone','ondansetron','major','Additive QT prolongation — torsades de pointes risk.'),
('amiodarone','propranolol','major','Beta-blocker + amiodarone — bradycardia / AV block.'),
('amiodarone','simvastatin','major','Amiodarone raises statin levels — myopathy risk.'),
('amiodarone','timolol','moderate','Topical beta-blocker — additive bradycardia.'),
('amiodarone','warfarin','major','Amiodarone raises warfarin effect — bleeding risk.'),
('amitriptyline','brimonidine','moderate','Brimonidine + TCA — may blunt effect / BP effects.'),
('amitriptyline','linezolid','major','Linezolid (MAOI) + serotonergic — serotonin syndrome risk.'),
('amitriptyline','tramadol','moderate','Tramadol + TCA — serotonin/seizure risk.'),
('amoxicillin','methotrexate','moderate','Penicillin may raise methotrexate levels.'),
('apixaban','carbamazepine','major','Enzyme inducer lowers DOAC levels — clot risk.'),
('apixaban','celecoxib','major','NSAID + anticoagulant — markedly increased bleeding risk.'),
('apixaban','citalopram','moderate','SSRI/SNRI + anticoagulant — increased bleeding risk.'),
('apixaban','clarithromycin','major','Macrolide raises DOAC levels — bleeding risk.'),
('apixaban','clopidogrel','major','Antiplatelet + anticoagulant — increased bleeding risk.'),
('apixaban','diclofenac','major','NSAID + anticoagulant — markedly increased bleeding risk.'),
('apixaban','duloxetine','moderate','SSRI/SNRI + anticoagulant — increased bleeding risk.'),
('apixaban','erythromycin','major','Macrolide raises DOAC levels — bleeding risk.'),
('apixaban','escitalopram','moderate','SSRI/SNRI + anticoagulant — increased bleeding risk.'),
('apixaban','etoricoxib','major','NSAID + anticoagulant — markedly increased bleeding risk.'),
('apixaban','fluconazole','major','Azole antifungal raises DOAC levels — bleeding risk.'),
('apixaban','fluoxetine','moderate','SSRI/SNRI + anticoagulant — increased bleeding risk.'),
('apixaban','fluvoxamine','moderate','SSRI/SNRI + anticoagulant — increased bleeding risk.'),
('apixaban','ibuprofen','major','NSAID + anticoagulant — markedly increased bleeding risk.'),
('apixaban','indomethacin','major','NSAID + anticoagulant — markedly increased bleeding risk.'),
('apixaban','itraconazole','major','Azole antifungal raises DOAC levels — bleeding risk.'),
('apixaban','ketoconazole','major','Azole antifungal raises DOAC levels — bleeding risk.'),
('apixaban','ketorolac','contraindicated','Ketorolac + anticoagulant — high GI/bleeding risk; avoid.'),
('apixaban','mefenamic','major','NSAID + anticoagulant — markedly increased bleeding risk.'),
('apixaban','meloxicam','major','NSAID + anticoagulant — markedly increased bleeding risk.'),
('apixaban','naproxen','major','NSAID + anticoagulant — markedly increased bleeding risk.'),
('apixaban','paroxetine','moderate','SSRI/SNRI + anticoagulant — increased bleeding risk.'),
('apixaban','phenytoin','major','Enzyme inducer lowers DOAC levels — clot risk.'),
('apixaban','piroxicam','major','NSAID + anticoagulant — markedly increased bleeding risk.'),
('apixaban','rifampicin','major','Enzyme inducer lowers DOAC levels — clot risk.'),
('apixaban','sertraline','moderate','SSRI/SNRI + anticoagulant — increased bleeding risk.'),
('apixaban','venlafaxine','moderate','SSRI/SNRI + anticoagulant — increased bleeding risk.'),
('atenolol','betaxolol','moderate','Topical + systemic beta-blocker — additive bradycardia.'),
('atenolol','clonidine','moderate','Beta-blocker + clonidine — rebound hypertension / bradycardia.'),
('atenolol','diltiazem','major','Beta-blocker + verapamil/diltiazem — bradycardia / AV block.'),
('atenolol','glibenclamide','moderate','Beta-blocker masks sulfonylurea hypoglycemia.'),
('atenolol','gliclazide','moderate','Beta-blocker masks sulfonylurea hypoglycemia.'),
('atenolol','glimepiride','moderate','Beta-blocker masks sulfonylurea hypoglycemia.'),
('atenolol','timolol','moderate','Topical + systemic beta-blocker — additive bradycardia.'),
('atenolol','verapamil','major','Beta-blocker + verapamil/diltiazem — bradycardia / AV block.'),
('atorvastatin','carbamazepine','moderate','Enzyme inducer lowers statin levels.'),
('atorvastatin','clarithromycin','major','Raises statin levels — rhabdomyolysis risk.'),
('atorvastatin','colchicine','major','Statin + colchicine — myopathy/rhabdomyolysis risk.'),
('atorvastatin','diltiazem','moderate','Verapamil/diltiazem raises statin levels — myopathy.'),
('atorvastatin','erythromycin','major','Raises statin levels — rhabdomyolysis risk.'),
('atorvastatin','fenofibrate','moderate','Statin + fibrate — myopathy risk.'),
('atorvastatin','fluconazole','major','Azole raises statin levels — myopathy risk.'),
('atorvastatin','gemfibrozil','major','Statin + gemfibrozil — high rhabdomyolysis risk.'),
('atorvastatin','itraconazole','major','Azole raises statin levels — myopathy risk.'),
('atorvastatin','ketoconazole','major','Azole raises statin levels — myopathy risk.'),
('atorvastatin','phenytoin','moderate','Enzyme inducer lowers statin levels.'),
('atorvastatin','rifampicin','moderate','Enzyme inducer lowers statin levels.'),
('atorvastatin','verapamil','moderate','Verapamil/diltiazem raises statin levels — myopathy.'),
('atorvastatin','warfarin','minor','Statin may modestly raise INR with warfarin.'),
('azithromycin','warfarin','major','Antibiotic potentiates warfarin — raised INR / bleeding.'),
('baclofen','codeine','major','Opioid + muscle relaxant — CNS/respiratory depression.'),
('baclofen','gabapentin','moderate','Additive CNS sedation.'),
('baclofen','pregabalin','moderate','Additive CNS sedation.'),
('baclofen','tramadol','major','Opioid + muscle relaxant — CNS/respiratory depression.'),
('betamethasone','carbamazepine','moderate','Enzyme inducer lowers corticosteroid effect.'),
('betamethasone','celecoxib','moderate','NSAID + corticosteroid — additive GI ulcer/bleeding risk.'),
('betamethasone','ciprofloxacin','moderate','Corticosteroid + quinolone — tendon rupture risk.'),
('betamethasone','diclofenac','moderate','NSAID + corticosteroid — additive GI ulcer/bleeding risk.'),
('betamethasone','etoricoxib','moderate','NSAID + corticosteroid — additive GI ulcer/bleeding risk.'),
('betamethasone','furosemide','moderate','Corticosteroid + diuretic — additive hypokalemia.'),
('betamethasone','glibenclamide','moderate','Corticosteroid raises blood glucose — reduces antidiabetic effect.'),
('betamethasone','gliclazide','moderate','Corticosteroid raises blood glucose — reduces antidiabetic effect.'),
('betamethasone','glimepiride','moderate','Corticosteroid raises blood glucose — reduces antidiabetic effect.'),
('betamethasone','hydrochlorothiazide','moderate','Corticosteroid + diuretic — additive hypokalemia.'),
('betamethasone','ibuprofen','moderate','NSAID + corticosteroid — additive GI ulcer/bleeding risk.'),
('betamethasone','indapamide','moderate','Corticosteroid + diuretic — additive hypokalemia.'),
('betamethasone','indomethacin','moderate','NSAID + corticosteroid — additive GI ulcer/bleeding risk.'),
('betamethasone','ketorolac','moderate','NSAID + corticosteroid — additive GI ulcer/bleeding risk.'),
('betamethasone','levofloxacin','moderate','Corticosteroid + quinolone — tendon rupture risk.'),
('betamethasone','mefenamic','moderate','NSAID + corticosteroid — additive GI ulcer/bleeding risk.'),
('betamethasone','meloxicam','moderate','NSAID + corticosteroid — additive GI ulcer/bleeding risk.'),
('betamethasone','moxifloxacin','moderate','Corticosteroid + quinolone — tendon rupture risk.'),
('betamethasone','naproxen','moderate','NSAID + corticosteroid — additive GI ulcer/bleeding risk.'),
('betamethasone','ofloxacin','moderate','Corticosteroid + quinolone — tendon rupture risk.'),
('betamethasone','phenytoin','moderate','Enzyme inducer lowers corticosteroid effect.'),
('betamethasone','piroxicam','moderate','NSAID + corticosteroid — additive GI ulcer/bleeding risk.'),
('betamethasone','rifampicin','moderate','Enzyme inducer lowers corticosteroid effect.'),
('betamethasone','warfarin','moderate','Corticosteroid can alter INR with warfarin.'),
('betaxolol','bisoprolol','moderate','Topical + systemic beta-blocker — additive bradycardia.'),
('betaxolol','carvedilol','moderate','Topical + systemic beta-blocker — additive bradycardia.'),
('betaxolol','digoxin','moderate','Topical beta-blocker — additive bradycardia.'),
('betaxolol','diltiazem','moderate','Topical beta-blocker + verapamil/diltiazem — bradycardia.'),
('betaxolol','metoprolol','moderate','Topical + systemic beta-blocker — additive bradycardia.'),
('betaxolol','propranolol','moderate','Topical + systemic beta-blocker — additive bradycardia.'),
('betaxolol','verapamil','moderate','Topical beta-blocker + verapamil/diltiazem — bradycardia.'),
('bisoprolol','clonidine','moderate','Beta-blocker + clonidine — rebound hypertension / bradycardia.'),
('bisoprolol','diltiazem','major','Beta-blocker + verapamil/diltiazem — bradycardia / AV block.'),
('bisoprolol','glibenclamide','moderate','Beta-blocker masks sulfonylurea hypoglycemia.'),
('bisoprolol','gliclazide','moderate','Beta-blocker masks sulfonylurea hypoglycemia.'),
('bisoprolol','glimepiride','moderate','Beta-blocker masks sulfonylurea hypoglycemia.'),
('bisoprolol','timolol','moderate','Topical + systemic beta-blocker — additive bradycardia.'),
('bisoprolol','verapamil','major','Beta-blocker + verapamil/diltiazem — bradycardia / AV block.'),
('brimonidine','codeine','moderate','Brimonidine + CNS depressant — additive sedation/hypotension.'),
('brimonidine','gabapentin','moderate','Brimonidine + CNS depressant — additive sedation/hypotension.'),
('brimonidine','pregabalin','moderate','Brimonidine + CNS depressant — additive sedation/hypotension.'),
('brimonidine','selegiline','contraindicated','Brimonidine + MAOI — hypertensive reaction; avoid.'),
('brimonidine','tramadol','moderate','Brimonidine + CNS depressant — additive sedation/hypotension.'),
('candesartan','celecoxib','moderate','NSAID reduces ACE/ARB effect and adds renal risk.'),
('candesartan','diclofenac','moderate','NSAID reduces ACE/ARB effect and adds renal risk.'),
('candesartan','etoricoxib','moderate','NSAID reduces ACE/ARB effect and adds renal risk.'),
('candesartan','ibuprofen','moderate','NSAID reduces ACE/ARB effect and adds renal risk.'),
('candesartan','indomethacin','moderate','NSAID reduces ACE/ARB effect and adds renal risk.'),
('candesartan','ketorolac','moderate','NSAID reduces ACE/ARB effect and adds renal risk.'),
('candesartan','lithium','major','ACE/ARB raises lithium levels — toxicity.'),
('candesartan','mefenamic','moderate','NSAID reduces ACE/ARB effect and adds renal risk.'),
('candesartan','meloxicam','moderate','NSAID reduces ACE/ARB effect and adds renal risk.'),
('candesartan','naproxen','moderate','NSAID reduces ACE/ARB effect and adds renal risk.'),
('candesartan','piroxicam','moderate','NSAID reduces ACE/ARB effect and adds renal risk.'),
('candesartan','potassium chloride','major','ACE/ARB + potassium — hyperkalemia.'),
('candesartan','spironolactone','major','ACE/ARB + potassium-sparing diuretic — hyperkalemia.'),
('candesartan','tizanidine','moderate','Tizanidine + antihypertensive — additive hypotension.'),
('candesartan','trimethoprim','moderate','ACE/ARB + trimethoprim — hyperkalemia risk.'),
('carbamazepine','clarithromycin','major','Macrolide raises carbamazepine — toxicity.'),
('carbamazepine','dabigatran','major','Enzyme inducer lowers DOAC levels — clot risk.'),
('carbamazepine','dexamethasone','moderate','Enzyme inducer lowers corticosteroid effect.'),
('carbamazepine','erythromycin','major','Macrolide raises carbamazepine — toxicity.'),
('carbamazepine','fluconazole','major','Azole raises carbamazepine — toxicity.'),
('carbamazepine','itraconazole','major','Azole raises carbamazepine — toxicity.'),
('carbamazepine','ketoconazole','major','Azole raises carbamazepine — toxicity.'),
('carbamazepine','methylprednisolone','moderate','Enzyme inducer lowers corticosteroid effect.'),
('carbamazepine','prednisolone','moderate','Enzyme inducer lowers corticosteroid effect.'),
('carbamazepine','rivaroxaban','major','Enzyme inducer lowers DOAC levels — clot risk.'),
('carbamazepine','simvastatin','moderate','Enzyme inducer lowers statin levels.'),
('carbamazepine','tramadol','moderate','Carbamazepine lowers tramadol effect; seizure risk.'),
('carvedilol','clonidine','moderate','Beta-blocker + clonidine — rebound hypertension / bradycardia.'),
('carvedilol','diltiazem','major','Beta-blocker + verapamil/diltiazem — bradycardia / AV block.'),
('carvedilol','glibenclamide','moderate','Beta-blocker masks sulfonylurea hypoglycemia.'),
('carvedilol','gliclazide','moderate','Beta-blocker masks sulfonylurea hypoglycemia.'),
('carvedilol','glimepiride','moderate','Beta-blocker masks sulfonylurea hypoglycemia.'),
('carvedilol','timolol','moderate','Topical + systemic beta-blocker — additive bradycardia.'),
('carvedilol','verapamil','major','Beta-blocker + verapamil/diltiazem — bradycardia / AV block.'),
('celecoxib','ciprofloxacin','minor','Quinolone + NSAID — slight seizure-threshold lowering.'),
('celecoxib','clopidogrel','moderate','NSAID + antiplatelet — increased GI/bleeding risk.'),
('celecoxib','dabigatran','major','NSAID + anticoagulant — markedly increased bleeding risk.'),
('celecoxib','dexamethasone','moderate','NSAID + corticosteroid — additive GI ulcer/bleeding risk.'),
('celecoxib','diclofenac','moderate','Two NSAIDs — additive GI ulcer / renal risk; avoid combining.'),
('celecoxib','digoxin','moderate','NSAID may raise digoxin levels.'),
('celecoxib','enalapril','moderate','NSAID reduces ACE/ARB effect and adds renal risk.'),
('celecoxib','enoxaparin','major','NSAID + anticoagulant — markedly increased bleeding risk.'),
('celecoxib','etoricoxib','moderate','Two NSAIDs — additive GI ulcer / renal risk; avoid combining.'),
('celecoxib','furosemide','moderate','NSAID reduces diuretic effect; renal risk.'),
('celecoxib','glibenclamide','minor','NSAID may enhance sulfonylurea hypoglycemia.'),
('celecoxib','gliclazide','minor','NSAID may enhance sulfonylurea hypoglycemia.'),
('celecoxib','glimepiride','minor','NSAID may enhance sulfonylurea hypoglycemia.'),
('celecoxib','heparin','major','NSAID + anticoagulant — markedly increased bleeding risk.'),
('celecoxib','hydrochlorothiazide','moderate','NSAID reduces diuretic effect; renal risk.'),
('celecoxib','ibuprofen','moderate','Two NSAIDs — additive GI ulcer / renal risk; avoid combining.'),
('celecoxib','indapamide','moderate','NSAID reduces diuretic effect; renal risk.'),
('celecoxib','indomethacin','moderate','Two NSAIDs — additive GI ulcer / renal risk; avoid combining.'),
('celecoxib','ketorolac','moderate','Two NSAIDs — additive GI ulcer / renal risk; avoid combining.'),
('celecoxib','levofloxacin','minor','Quinolone + NSAID — slight seizure-threshold lowering.'),
('celecoxib','lisinopril','moderate','NSAID reduces ACE/ARB effect and adds renal risk.'),
('celecoxib','lithium','major','NSAID raises lithium levels — toxicity.'),
('celecoxib','losartan','moderate','NSAID reduces ACE/ARB effect and adds renal risk.'),
('celecoxib','mefenamic','moderate','Two NSAIDs — additive GI ulcer / renal risk; avoid combining.'),
('celecoxib','meloxicam','moderate','Two NSAIDs — additive GI ulcer / renal risk; avoid combining.'),
('celecoxib','methotrexate','major','NSAID raises methotrexate toxicity.'),
('celecoxib','methylprednisolone','moderate','NSAID + corticosteroid — additive GI ulcer/bleeding risk.'),
('celecoxib','moxifloxacin','minor','Quinolone + NSAID — slight seizure-threshold lowering.'),
('celecoxib','naproxen','moderate','Two NSAIDs — additive GI ulcer / renal risk; avoid combining.'),
('celecoxib','ofloxacin','minor','Quinolone + NSAID — slight seizure-threshold lowering.'),
('celecoxib','piroxicam','moderate','Two NSAIDs — additive GI ulcer / renal risk; avoid combining.'),
('celecoxib','prednisolone','moderate','NSAID + corticosteroid — additive GI ulcer/bleeding risk.'),
('celecoxib','ramipril','moderate','NSAID reduces ACE/ARB effect and adds renal risk.'),
('celecoxib','risedronate','moderate','NSAID + bisphosphonate — additive GI/esophageal irritation.'),
('celecoxib','rivaroxaban','major','NSAID + anticoagulant — markedly increased bleeding risk.'),
('celecoxib','spironolactone','moderate','NSAID + spironolactone — hyperkalemia / renal risk.'),
('celecoxib','telmisartan','moderate','NSAID reduces ACE/ARB effect and adds renal risk.'),
('celecoxib','valsartan','moderate','NSAID reduces ACE/ARB effect and adds renal risk.'),
('celecoxib','warfarin','major','NSAID + anticoagulant — markedly increased bleeding risk.'),
('celecoxib','zoledronic','moderate','NSAID + bisphosphonate — additive GI/esophageal irritation.'),
('ciprofloxacin','dexamethasone','moderate','Corticosteroid + quinolone — tendon rupture risk.'),
('ciprofloxacin','diclofenac','minor','Quinolone + NSAID — slight seizure-threshold lowering.'),
('ciprofloxacin','etoricoxib','minor','Quinolone + NSAID — slight seizure-threshold lowering.'),
('ciprofloxacin','glibenclamide','moderate','Quinolone + sulfonylurea — dysglycemia.'),
('ciprofloxacin','gliclazide','moderate','Quinolone + sulfonylurea — dysglycemia.'),
('ciprofloxacin','glimepiride','moderate','Quinolone + sulfonylurea — dysglycemia.'),
('ciprofloxacin','ibuprofen','minor','Quinolone + NSAID — slight seizure-threshold lowering.'),
('ciprofloxacin','indomethacin','minor','Quinolone + NSAID — slight seizure-threshold lowering.'),
('ciprofloxacin','ketorolac','minor','Quinolone + NSAID — slight seizure-threshold lowering.'),
('ciprofloxacin','mefenamic','minor','Quinolone + NSAID — slight seizure-threshold lowering.'),
('ciprofloxacin','meloxicam','minor','Quinolone + NSAID — slight seizure-threshold lowering.'),
('ciprofloxacin','methylprednisolone','moderate','Corticosteroid + quinolone — tendon rupture risk.'),
('ciprofloxacin','naproxen','minor','Quinolone + NSAID — slight seizure-threshold lowering.'),
('ciprofloxacin','piroxicam','minor','Quinolone + NSAID — slight seizure-threshold lowering.'),
('ciprofloxacin','prednisolone','moderate','Corticosteroid + quinolone — tendon rupture risk.'),
('ciprofloxacin','sucralfate','moderate','Sucralfate reduces quinolone absorption — separate doses.'),
('ciprofloxacin','theophylline','major','Raises theophylline levels — toxicity.'),
('ciprofloxacin','tizanidine','contraindicated','CYP1A2 inhibitor + tizanidine — severe hypotension/sedation; avoid.'),
('ciprofloxacin','warfarin','major','Antibiotic potentiates warfarin — raised INR / bleeding.'),
('citalopram','clarithromycin','major','Additive QT prolongation — torsades de pointes risk.'),
('citalopram','clopidogrel','moderate','SSRI/SNRI + antiplatelet — increased GI bleeding risk.'),
('citalopram','dabigatran','moderate','SSRI/SNRI + anticoagulant — increased bleeding risk.'),
('citalopram','domperidone','major','Additive QT prolongation — torsades de pointes risk.'),
('citalopram','enoxaparin','moderate','SSRI/SNRI + anticoagulant — increased bleeding risk.'),
('citalopram','escitalopram','major','Additive QT prolongation — torsades de pointes risk.'),
('citalopram','haloperidol','major','Additive QT prolongation — torsades de pointes risk.'),
('citalopram','heparin','moderate','SSRI/SNRI + anticoagulant — increased bleeding risk.'),
('citalopram','linezolid','major','Linezolid (MAOI) + serotonergic — serotonin syndrome risk.'),
('citalopram','moxifloxacin','major','Additive QT prolongation — torsades de pointes risk.'),
('citalopram','naratriptan','moderate','Triptan + SSRI/SNRI — serotonin syndrome risk.'),
('citalopram','ondansetron','major','Additive QT prolongation — torsades de pointes risk.'),
('citalopram','rivaroxaban','moderate','SSRI/SNRI + anticoagulant — increased bleeding risk.'),
('citalopram','sumatriptan','moderate','Triptan + SSRI/SNRI — serotonin syndrome risk.'),
('citalopram','tramadol','major','Tramadol + SSRI/SNRI — serotonin syndrome and seizure risk.'),
('citalopram','warfarin','moderate','SSRI/SNRI + anticoagulant — increased bleeding risk.'),
('clarithromycin','colchicine','contraindicated','Clarithromycin + colchicine — fatal colchicine toxicity; avoid.'),
('clarithromycin','dabigatran','major','Macrolide raises DOAC levels — bleeding risk.'),
('clarithromycin','digoxin','major','Macrolide raises digoxin levels — toxicity.'),
('clarithromycin','domperidone','major','Additive QT prolongation — torsades de pointes risk.'),
('clarithromycin','ergotamine','major','Raises ergotamine — ergotism (vasospasm).'),
('clarithromycin','escitalopram','major','Additive QT prolongation — torsades de pointes risk.'),
('clarithromycin','haloperidol','major','Additive QT prolongation — torsades de pointes risk.'),
('clarithromycin','moxifloxacin','major','Additive QT prolongation — torsades de pointes risk.'),
('clarithromycin','ondansetron','major','Additive QT prolongation — torsades de pointes risk.'),
('clarithromycin','rivaroxaban','major','Macrolide raises DOAC levels — bleeding risk.'),
('clarithromycin','sildenafil','moderate','Raises PDE5-inhibitor levels — hypotension.'),
('clarithromycin','simvastatin','major','Raises statin levels — rhabdomyolysis risk.'),
('clarithromycin','tadalafil','moderate','Raises PDE5-inhibitor levels — hypotension.'),
('clarithromycin','theophylline','major','Macrolide raises theophylline — toxicity.'),
('clarithromycin','vardenafil','moderate','Raises PDE5-inhibitor levels — hypotension.'),
('clarithromycin','warfarin','major','Antibiotic potentiates warfarin — raised INR / bleeding.'),
('clonidine','metoprolol','moderate','Beta-blocker + clonidine — rebound hypertension / bradycardia.'),
('clonidine','propranolol','moderate','Beta-blocker + clonidine — rebound hypertension / bradycardia.'),
('clopidogrel','dabigatran','major','Antiplatelet + anticoagulant — increased bleeding risk.'),
('clopidogrel','diclofenac','moderate','NSAID + antiplatelet — increased GI/bleeding risk.'),
('clopidogrel','duloxetine','moderate','SSRI/SNRI + antiplatelet — increased GI bleeding risk.'),
('clopidogrel','enoxaparin','major','Antiplatelet + anticoagulant — increased bleeding risk.'),
('clopidogrel','escitalopram','moderate','SSRI/SNRI + antiplatelet — increased GI bleeding risk.'),
('clopidogrel','esomeprazole','moderate','PPI may reduce clopidogrel activation.'),
('clopidogrel','etoricoxib','moderate','NSAID + antiplatelet — increased GI/bleeding risk.'),
('clopidogrel','fluoxetine','moderate','SSRI/SNRI + antiplatelet — increased GI bleeding risk.'),
('clopidogrel','fluvoxamine','moderate','SSRI/SNRI + antiplatelet — increased GI bleeding risk.'),
('clopidogrel','heparin','major','Antiplatelet + anticoagulant — increased bleeding risk.'),
('clopidogrel','ibuprofen','moderate','NSAID + antiplatelet — increased GI/bleeding risk.'),
('clopidogrel','indomethacin','moderate','NSAID + antiplatelet — increased GI/bleeding risk.'),
('clopidogrel','ketorolac','major','Ketorolac + antiplatelet — high GI/bleeding risk.'),
('clopidogrel','mefenamic','moderate','NSAID + antiplatelet — increased GI/bleeding risk.'),
('clopidogrel','meloxicam','moderate','NSAID + antiplatelet — increased GI/bleeding risk.'),
('clopidogrel','naproxen','moderate','NSAID + antiplatelet — increased GI/bleeding risk.'),
('clopidogrel','omeprazole','moderate','PPI may reduce clopidogrel activation.'),
('clopidogrel','paroxetine','moderate','SSRI/SNRI + antiplatelet — increased GI bleeding risk.'),
('clopidogrel','piroxicam','moderate','NSAID + antiplatelet — increased GI/bleeding risk.'),
('clopidogrel','rivaroxaban','major','Antiplatelet + anticoagulant — increased bleeding risk.'),
('clopidogrel','sertraline','moderate','SSRI/SNRI + antiplatelet — increased GI bleeding risk.'),
('clopidogrel','venlafaxine','moderate','SSRI/SNRI + antiplatelet — increased GI bleeding risk.'),
('clopidogrel','warfarin','major','Antiplatelet + anticoagulant — increased bleeding risk.'),
('codeine','gabapentin','major','Opioid + gabapentinoid — respiratory depression / sedation.'),
('codeine','pregabalin','major','Opioid + gabapentinoid — respiratory depression / sedation.'),
('codeine','tizanidine','major','Opioid + muscle relaxant — CNS/respiratory depression.'),
('colchicine','diltiazem','major','Raises colchicine levels — toxicity risk.'),
('colchicine','erythromycin','major','Raises colchicine levels — toxicity risk.'),
('colchicine','itraconazole','major','Raises colchicine levels — toxicity risk.'),
('colchicine','ketoconazole','major','Raises colchicine levels — toxicity risk.'),
('colchicine','rosuvastatin','major','Statin + colchicine — myopathy/rhabdomyolysis risk.'),
('colchicine','simvastatin','major','Statin + colchicine — myopathy/rhabdomyolysis risk.'),
('colchicine','verapamil','major','Raises colchicine levels — toxicity risk.'),
('dabigatran','diclofenac','major','NSAID + anticoagulant — markedly increased bleeding risk.'),
('dabigatran','diltiazem','moderate','Verapamil/diltiazem raises dabigatran levels.'),
('dabigatran','duloxetine','moderate','SSRI/SNRI + anticoagulant — increased bleeding risk.'),
('dabigatran','erythromycin','major','Macrolide raises DOAC levels — bleeding risk.'),
('dabigatran','escitalopram','moderate','SSRI/SNRI + anticoagulant — increased bleeding risk.'),
('dabigatran','etoricoxib','major','NSAID + anticoagulant — markedly increased bleeding risk.'),
('dabigatran','fluconazole','major','Azole antifungal raises DOAC levels — bleeding risk.'),
('dabigatran','fluoxetine','moderate','SSRI/SNRI + anticoagulant — increased bleeding risk.'),
('dabigatran','fluvoxamine','moderate','SSRI/SNRI + anticoagulant — increased bleeding risk.'),
('dabigatran','ibuprofen','major','NSAID + anticoagulant — markedly increased bleeding risk.'),
('dabigatran','indomethacin','major','NSAID + anticoagulant — markedly increased bleeding risk.'),
('dabigatran','itraconazole','major','Azole antifungal raises DOAC levels — bleeding risk.'),
('dabigatran','ketoconazole','major','Azole antifungal raises DOAC levels — bleeding risk.'),
('dabigatran','ketorolac','contraindicated','Ketorolac + anticoagulant — high GI/bleeding risk; avoid.'),
('dabigatran','mefenamic','major','NSAID + anticoagulant — markedly increased bleeding risk.'),
('dabigatran','meloxicam','major','NSAID + anticoagulant — markedly increased bleeding risk.'),
('dabigatran','naproxen','major','NSAID + anticoagulant — markedly increased bleeding risk.'),
('dabigatran','paroxetine','moderate','SSRI/SNRI + anticoagulant — increased bleeding risk.'),
('dabigatran','phenytoin','major','Enzyme inducer lowers DOAC levels — clot risk.'),
('dabigatran','piroxicam','major','NSAID + anticoagulant — markedly increased bleeding risk.'),
('dabigatran','rifampicin','major','Enzyme inducer lowers DOAC levels — clot risk.'),
('dabigatran','sertraline','moderate','SSRI/SNRI + anticoagulant — increased bleeding risk.'),
('dabigatran','venlafaxine','moderate','SSRI/SNRI + anticoagulant — increased bleeding risk.'),
('dabigatran','verapamil','moderate','Verapamil/diltiazem raises dabigatran levels.'),
('dexamethasone','diclofenac','moderate','NSAID + corticosteroid — additive GI ulcer/bleeding risk.'),
('dexamethasone','etoricoxib','moderate','NSAID + corticosteroid — additive GI ulcer/bleeding risk.'),
('dexamethasone','furosemide','moderate','Corticosteroid + diuretic — additive hypokalemia.'),
('dexamethasone','glibenclamide','moderate','Corticosteroid raises blood glucose — reduces antidiabetic effect.'),
('dexamethasone','gliclazide','moderate','Corticosteroid raises blood glucose — reduces antidiabetic effect.'),
('dexamethasone','glimepiride','moderate','Corticosteroid raises blood glucose — reduces antidiabetic effect.'),
('dexamethasone','hydrochlorothiazide','moderate','Corticosteroid + diuretic — additive hypokalemia.'),
('dexamethasone','ibuprofen','moderate','NSAID + corticosteroid — additive GI ulcer/bleeding risk.'),
('dexamethasone','indapamide','moderate','Corticosteroid + diuretic — additive hypokalemia.'),
('dexamethasone','indomethacin','moderate','NSAID + corticosteroid — additive GI ulcer/bleeding risk.'),
('dexamethasone','ketorolac','moderate','NSAID + corticosteroid — additive GI ulcer/bleeding risk.'),
('dexamethasone','levofloxacin','moderate','Corticosteroid + quinolone — tendon rupture risk.'),
('dexamethasone','mefenamic','moderate','NSAID + corticosteroid — additive GI ulcer/bleeding risk.'),
('dexamethasone','meloxicam','moderate','NSAID + corticosteroid — additive GI ulcer/bleeding risk.'),
('dexamethasone','moxifloxacin','moderate','Corticosteroid + quinolone — tendon rupture risk.'),
('dexamethasone','naproxen','moderate','NSAID + corticosteroid — additive GI ulcer/bleeding risk.'),
('dexamethasone','ofloxacin','moderate','Corticosteroid + quinolone — tendon rupture risk.'),
('dexamethasone','phenytoin','moderate','Enzyme inducer lowers corticosteroid effect.'),
('dexamethasone','piroxicam','moderate','NSAID + corticosteroid — additive GI ulcer/bleeding risk.'),
('dexamethasone','rifampicin','moderate','Enzyme inducer lowers corticosteroid effect.'),
('dexamethasone','warfarin','moderate','Corticosteroid can alter INR with warfarin.'),
('diclofenac','digoxin','moderate','NSAID may raise digoxin levels.'),
('diclofenac','enalapril','moderate','NSAID reduces ACE/ARB effect and adds renal risk.'),
('diclofenac','enoxaparin','major','NSAID + anticoagulant — markedly increased bleeding risk.'),
('diclofenac','etoricoxib','moderate','Two NSAIDs — additive GI ulcer / renal risk; avoid combining.'),
('diclofenac','furosemide','moderate','NSAID reduces diuretic effect; renal risk.'),
('diclofenac','glibenclamide','minor','NSAID may enhance sulfonylurea hypoglycemia.'),
('diclofenac','gliclazide','minor','NSAID may enhance sulfonylurea hypoglycemia.'),
('diclofenac','glimepiride','minor','NSAID may enhance sulfonylurea hypoglycemia.'),
('diclofenac','heparin','major','NSAID + anticoagulant — markedly increased bleeding risk.'),
('diclofenac','hydrochlorothiazide','moderate','NSAID reduces diuretic effect; renal risk.'),
('diclofenac','ibuprofen','moderate','Two NSAIDs — additive GI ulcer / renal risk; avoid combining.'),
('diclofenac','indapamide','moderate','NSAID reduces diuretic effect; renal risk.'),
('diclofenac','indomethacin','moderate','Two NSAIDs — additive GI ulcer / renal risk; avoid combining.'),
('diclofenac','ketorolac','moderate','Two NSAIDs — additive GI ulcer / renal risk; avoid combining.'),
('diclofenac','levofloxacin','minor','Quinolone + NSAID — slight seizure-threshold lowering.'),
('diclofenac','lisinopril','moderate','NSAID reduces ACE/ARB effect and adds renal risk.'),
('diclofenac','lithium','major','NSAID raises lithium levels — toxicity.'),
('diclofenac','losartan','moderate','NSAID reduces ACE/ARB effect and adds renal risk.'),
('diclofenac','mefenamic','moderate','Two NSAIDs — additive GI ulcer / renal risk; avoid combining.'),
('diclofenac','meloxicam','moderate','Two NSAIDs — additive GI ulcer / renal risk; avoid combining.'),
('diclofenac','methotrexate','major','NSAID raises methotrexate toxicity.'),
('diclofenac','methylprednisolone','moderate','NSAID + corticosteroid — additive GI ulcer/bleeding risk.'),
('diclofenac','moxifloxacin','minor','Quinolone + NSAID — slight seizure-threshold lowering.'),
('diclofenac','naproxen','moderate','Two NSAIDs — additive GI ulcer / renal risk; avoid combining.'),
('diclofenac','ofloxacin','minor','Quinolone + NSAID — slight seizure-threshold lowering.'),
('diclofenac','piroxicam','moderate','Two NSAIDs — additive GI ulcer / renal risk; avoid combining.'),
('diclofenac','prednisolone','moderate','NSAID + corticosteroid — additive GI ulcer/bleeding risk.'),
('diclofenac','ramipril','moderate','NSAID reduces ACE/ARB effect and adds renal risk.'),
('diclofenac','risedronate','moderate','NSAID + bisphosphonate — additive GI/esophageal irritation.'),
('diclofenac','rivaroxaban','major','NSAID + anticoagulant — markedly increased bleeding risk.'),
('diclofenac','spironolactone','moderate','NSAID + spironolactone — hyperkalemia / renal risk.'),
('diclofenac','telmisartan','moderate','NSAID reduces ACE/ARB effect and adds renal risk.'),
('diclofenac','valsartan','moderate','NSAID reduces ACE/ARB effect and adds renal risk.'),
('diclofenac','warfarin','major','NSAID + anticoagulant — markedly increased bleeding risk.'),
('diclofenac','zoledronic','moderate','NSAID + bisphosphonate — additive GI/esophageal irritation.'),
('digoxin','diltiazem','major','Raises digoxin levels — toxicity.'),
('digoxin','erythromycin','major','Macrolide raises digoxin levels — toxicity.'),
('digoxin','etoricoxib','moderate','NSAID may raise digoxin levels.'),
('digoxin','furosemide','moderate','Diuretic-induced hypokalemia raises digoxin toxicity.'),
('digoxin','hydrochlorothiazide','moderate','Diuretic-induced hypokalemia raises digoxin toxicity.'),
('digoxin','ibuprofen','moderate','NSAID may raise digoxin levels.'),
('digoxin','indapamide','moderate','Diuretic-induced hypokalemia raises digoxin toxicity.'),
('digoxin','indomethacin','moderate','NSAID may raise digoxin levels.'),
('digoxin','itraconazole','major','Raises digoxin levels — toxicity.'),
('digoxin','ketorolac','moderate','NSAID may raise digoxin levels.'),
('digoxin','mefenamic','moderate','NSAID may raise digoxin levels.'),
('digoxin','meloxicam','moderate','NSAID may raise digoxin levels.'),
('digoxin','naproxen','moderate','NSAID may raise digoxin levels.'),
('digoxin','piroxicam','moderate','NSAID may raise digoxin levels.'),
('digoxin','spironolactone','moderate','Spironolactone may raise digoxin levels.'),
('digoxin','timolol','moderate','Topical beta-blocker — additive bradycardia.'),
('digoxin','verapamil','major','Raises digoxin levels — toxicity.'),
('diltiazem','metoprolol','major','Beta-blocker + verapamil/diltiazem — bradycardia / AV block.'),
('diltiazem','propranolol','major','Beta-blocker + verapamil/diltiazem — bradycardia / AV block.'),
('diltiazem','simvastatin','moderate','Verapamil/diltiazem raises statin levels — myopathy.'),
('diltiazem','timolol','moderate','Topical beta-blocker + verapamil/diltiazem — bradycardia.'),
('domperidone','escitalopram','major','Additive QT prolongation — torsades de pointes risk.'),
('domperidone','haloperidol','major','Additive QT prolongation — torsades de pointes risk.'),
('domperidone','moxifloxacin','major','Additive QT prolongation — torsades de pointes risk.'),
('domperidone','ondansetron','major','Additive QT prolongation — torsades de pointes risk.'),
('doxycycline','warfarin','major','Antibiotic potentiates warfarin — raised INR / bleeding.'),
('duloxetine','enoxaparin','moderate','SSRI/SNRI + anticoagulant — increased bleeding risk.'),
('duloxetine','heparin','moderate','SSRI/SNRI + anticoagulant — increased bleeding risk.'),
('duloxetine','linezolid','major','Linezolid (MAOI) + serotonergic — serotonin syndrome risk.'),
('duloxetine','naratriptan','moderate','Triptan + SSRI/SNRI — serotonin syndrome risk.'),
('duloxetine','rivaroxaban','moderate','SSRI/SNRI + anticoagulant — increased bleeding risk.'),
('duloxetine','sumatriptan','moderate','Triptan + SSRI/SNRI — serotonin syndrome risk.'),
('duloxetine','tramadol','major','Tramadol + SSRI/SNRI — serotonin syndrome and seizure risk.'),
('duloxetine','warfarin','moderate','SSRI/SNRI + anticoagulant — increased bleeding risk.'),
('enalapril','etoricoxib','moderate','NSAID reduces ACE/ARB effect and adds renal risk.'),
('enalapril','ibuprofen','moderate','NSAID reduces ACE/ARB effect and adds renal risk.'),
('enalapril','indomethacin','moderate','NSAID reduces ACE/ARB effect and adds renal risk.'),
('enalapril','ketorolac','moderate','NSAID reduces ACE/ARB effect and adds renal risk.'),
('enalapril','lithium','major','ACE/ARB raises lithium levels — toxicity.'),
('enalapril','mefenamic','moderate','NSAID reduces ACE/ARB effect and adds renal risk.'),
('enalapril','meloxicam','moderate','NSAID reduces ACE/ARB effect and adds renal risk.'),
('enalapril','naproxen','moderate','NSAID reduces ACE/ARB effect and adds renal risk.'),
('enalapril','piroxicam','moderate','NSAID reduces ACE/ARB effect and adds renal risk.'),
('enalapril','potassium chloride','major','ACE/ARB + potassium — hyperkalemia.'),
('enalapril','spironolactone','major','ACE/ARB + potassium-sparing diuretic — hyperkalemia.'),
('enalapril','tizanidine','moderate','Tizanidine + antihypertensive — additive hypotension.'),
('enalapril','trimethoprim','moderate','ACE/ARB + trimethoprim — hyperkalemia risk.'),
('enoxaparin','escitalopram','moderate','SSRI/SNRI + anticoagulant — increased bleeding risk.'),
('enoxaparin','etoricoxib','major','NSAID + anticoagulant — markedly increased bleeding risk.'),
('enoxaparin','fluoxetine','moderate','SSRI/SNRI + anticoagulant — increased bleeding risk.'),
('enoxaparin','fluvoxamine','moderate','SSRI/SNRI + anticoagulant — increased bleeding risk.'),
('enoxaparin','ibuprofen','major','NSAID + anticoagulant — markedly increased bleeding risk.'),
('enoxaparin','indomethacin','major','NSAID + anticoagulant — markedly increased bleeding risk.'),
('enoxaparin','ketorolac','contraindicated','Ketorolac + anticoagulant — high GI/bleeding risk; avoid.'),
('enoxaparin','mefenamic','major','NSAID + anticoagulant — markedly increased bleeding risk.'),
('enoxaparin','meloxicam','major','NSAID + anticoagulant — markedly increased bleeding risk.'),
('enoxaparin','naproxen','major','NSAID + anticoagulant — markedly increased bleeding risk.'),
('enoxaparin','paroxetine','moderate','SSRI/SNRI + anticoagulant — increased bleeding risk.'),
('enoxaparin','piroxicam','major','NSAID + anticoagulant — markedly increased bleeding risk.'),
('enoxaparin','sertraline','moderate','SSRI/SNRI + anticoagulant — increased bleeding risk.'),
('enoxaparin','venlafaxine','moderate','SSRI/SNRI + anticoagulant — increased bleeding risk.'),
('ergotamine','erythromycin','major','Raises ergotamine — ergotism (vasospasm).'),
('ergotamine','fluconazole','major','Raises ergotamine — ergotism (vasospasm).'),
('ergotamine','itraconazole','major','Raises ergotamine — ergotism (vasospasm).'),
('ergotamine','ketoconazole','major','Raises ergotamine — ergotism (vasospasm).'),
('ergotamine','naratriptan','contraindicated','Triptan + ergotamine — coronary/peripheral vasospasm; avoid.'),
('ergotamine','sumatriptan','contraindicated','Triptan + ergotamine — coronary/peripheral vasospasm; avoid.'),
('erythromycin','rivaroxaban','major','Macrolide raises DOAC levels — bleeding risk.'),
('erythromycin','sildenafil','moderate','Raises PDE5-inhibitor levels — hypotension.'),
('erythromycin','simvastatin','major','Raises statin levels — rhabdomyolysis risk.'),
('erythromycin','tadalafil','moderate','Raises PDE5-inhibitor levels — hypotension.'),
('erythromycin','theophylline','major','Macrolide raises theophylline — toxicity.'),
('erythromycin','vardenafil','moderate','Raises PDE5-inhibitor levels — hypotension.'),
('erythromycin','warfarin','major','Antibiotic potentiates warfarin — raised INR / bleeding.'),
('escitalopram','haloperidol','major','Additive QT prolongation — torsades de pointes risk.'),
('escitalopram','heparin','moderate','SSRI/SNRI + anticoagulant — increased bleeding risk.'),
('escitalopram','linezolid','major','Linezolid (MAOI) + serotonergic — serotonin syndrome risk.'),
('escitalopram','moxifloxacin','major','Additive QT prolongation — torsades de pointes risk.'),
('escitalopram','naratriptan','moderate','Triptan + SSRI/SNRI — serotonin syndrome risk.'),
('escitalopram','ondansetron','major','Additive QT prolongation — torsades de pointes risk.'),
('escitalopram','rivaroxaban','moderate','SSRI/SNRI + anticoagulant — increased bleeding risk.'),
('escitalopram','sumatriptan','moderate','Triptan + SSRI/SNRI — serotonin syndrome risk.'),
('escitalopram','tramadol','major','Tramadol + SSRI/SNRI — serotonin syndrome and seizure risk.'),
('escitalopram','warfarin','moderate','SSRI/SNRI + anticoagulant — increased bleeding risk.'),
('esomeprazole','levothyroxine','moderate','PPI may reduce levothyroxine absorption.'),
('esomeprazole','methotrexate','moderate','PPI may raise methotrexate levels.'),
('etoricoxib','furosemide','moderate','NSAID reduces diuretic effect; renal risk.'),
('etoricoxib','glibenclamide','minor','NSAID may enhance sulfonylurea hypoglycemia.'),
('etoricoxib','gliclazide','minor','NSAID may enhance sulfonylurea hypoglycemia.'),
('etoricoxib','glimepiride','minor','NSAID may enhance sulfonylurea hypoglycemia.'),
('etoricoxib','heparin','major','NSAID + anticoagulant — markedly increased bleeding risk.'),
('etoricoxib','hydrochlorothiazide','moderate','NSAID reduces diuretic effect; renal risk.'),
('etoricoxib','ibuprofen','moderate','Two NSAIDs — additive GI ulcer / renal risk; avoid combining.'),
('etoricoxib','indapamide','moderate','NSAID reduces diuretic effect; renal risk.'),
('etoricoxib','indomethacin','moderate','Two NSAIDs — additive GI ulcer / renal risk; avoid combining.'),
('etoricoxib','ketorolac','moderate','Two NSAIDs — additive GI ulcer / renal risk; avoid combining.'),
('etoricoxib','levofloxacin','minor','Quinolone + NSAID — slight seizure-threshold lowering.'),
('etoricoxib','lisinopril','moderate','NSAID reduces ACE/ARB effect and adds renal risk.'),
('etoricoxib','lithium','major','NSAID raises lithium levels — toxicity.'),
('etoricoxib','losartan','moderate','NSAID reduces ACE/ARB effect and adds renal risk.'),
('etoricoxib','mefenamic','moderate','Two NSAIDs — additive GI ulcer / renal risk; avoid combining.'),
('etoricoxib','meloxicam','moderate','Two NSAIDs — additive GI ulcer / renal risk; avoid combining.'),
('etoricoxib','methotrexate','major','NSAID raises methotrexate toxicity.'),
('etoricoxib','methylprednisolone','moderate','NSAID + corticosteroid — additive GI ulcer/bleeding risk.'),
('etoricoxib','moxifloxacin','minor','Quinolone + NSAID — slight seizure-threshold lowering.'),
('etoricoxib','naproxen','moderate','Two NSAIDs — additive GI ulcer / renal risk; avoid combining.'),
('etoricoxib','ofloxacin','minor','Quinolone + NSAID — slight seizure-threshold lowering.'),
('etoricoxib','piroxicam','moderate','Two NSAIDs — additive GI ulcer / renal risk; avoid combining.'),
('etoricoxib','prednisolone','moderate','NSAID + corticosteroid — additive GI ulcer/bleeding risk.'),
('etoricoxib','ramipril','moderate','NSAID reduces ACE/ARB effect and adds renal risk.'),
('etoricoxib','risedronate','moderate','NSAID + bisphosphonate — additive GI/esophageal irritation.'),
('etoricoxib','rivaroxaban','major','NSAID + anticoagulant — markedly increased bleeding risk.'),
('etoricoxib','spironolactone','moderate','NSAID + spironolactone — hyperkalemia / renal risk.'),
('etoricoxib','telmisartan','moderate','NSAID reduces ACE/ARB effect and adds renal risk.'),
('etoricoxib','valsartan','moderate','NSAID reduces ACE/ARB effect and adds renal risk.'),
('etoricoxib','warfarin','major','NSAID + anticoagulant — markedly increased bleeding risk.'),
('etoricoxib','zoledronic','moderate','NSAID + bisphosphonate — additive GI/esophageal irritation.'),
('fenofibrate','rosuvastatin','moderate','Statin + fibrate — myopathy risk.'),
('fenofibrate','simvastatin','moderate','Statin + fibrate — myopathy risk.'),
('fluconazole','glibenclamide','major','Azole raises sulfonylurea — hypoglycemia.'),
('fluconazole','gliclazide','major','Azole raises sulfonylurea — hypoglycemia.'),
('fluconazole','glimepiride','major','Azole raises sulfonylurea — hypoglycemia.'),
('fluconazole','phenytoin','major','Azole raises phenytoin — toxicity.'),
('fluconazole','rifampicin','moderate','Inducer lowers azole levels / azole raises inducer.'),
('fluconazole','rivaroxaban','major','Azole antifungal raises DOAC levels — bleeding risk.'),
('fluconazole','simvastatin','major','Azole raises statin levels — myopathy risk.'),
('fluconazole','warfarin','major','Antibiotic potentiates warfarin — raised INR / bleeding.'),
('fluoxetine','heparin','moderate','SSRI/SNRI + anticoagulant — increased bleeding risk.'),
('fluoxetine','linezolid','major','Linezolid (MAOI) + serotonergic — serotonin syndrome risk.'),
('fluoxetine','naratriptan','moderate','Triptan + SSRI/SNRI — serotonin syndrome risk.'),
('fluoxetine','rivaroxaban','moderate','SSRI/SNRI + anticoagulant — increased bleeding risk.'),
('fluoxetine','sumatriptan','moderate','Triptan + SSRI/SNRI — serotonin syndrome risk.'),
('fluoxetine','tramadol','major','Tramadol + SSRI/SNRI — serotonin syndrome and seizure risk.'),
('fluoxetine','warfarin','moderate','SSRI/SNRI + anticoagulant — increased bleeding risk.'),
('fluvoxamine','heparin','moderate','SSRI/SNRI + anticoagulant — increased bleeding risk.'),
('fluvoxamine','linezolid','major','Linezolid (MAOI) + serotonergic — serotonin syndrome risk.'),
('fluvoxamine','naratriptan','moderate','Triptan + SSRI/SNRI — serotonin syndrome risk.'),
('fluvoxamine','rivaroxaban','moderate','SSRI/SNRI + anticoagulant — increased bleeding risk.'),
('fluvoxamine','sumatriptan','moderate','Triptan + SSRI/SNRI — serotonin syndrome risk.'),
('fluvoxamine','theophylline','major','Raises theophylline levels — toxicity.'),
('fluvoxamine','tizanidine','contraindicated','CYP1A2 inhibitor + tizanidine — severe hypotension/sedation; avoid.'),
('fluvoxamine','tramadol','major','Tramadol + SSRI/SNRI — serotonin syndrome and seizure risk.'),
('fluvoxamine','warfarin','moderate','SSRI/SNRI + anticoagulant — increased bleeding risk.'),
('furosemide','ibuprofen','moderate','NSAID reduces diuretic effect; renal risk.'),
('furosemide','indomethacin','moderate','NSAID reduces diuretic effect; renal risk.'),
('furosemide','ketorolac','moderate','NSAID reduces diuretic effect; renal risk.'),
('furosemide','lithium','major','Thiazide/loop diuretic raises lithium levels — toxicity.'),
('furosemide','mefenamic','moderate','NSAID reduces diuretic effect; renal risk.'),
('furosemide','meloxicam','moderate','NSAID reduces diuretic effect; renal risk.'),
('furosemide','methylprednisolone','moderate','Corticosteroid + diuretic — additive hypokalemia.'),
('furosemide','naproxen','moderate','NSAID reduces diuretic effect; renal risk.'),
('furosemide','piroxicam','moderate','NSAID reduces diuretic effect; renal risk.'),
('furosemide','prednisolone','moderate','Corticosteroid + diuretic — additive hypokalemia.'),
('gabapentin','pregabalin','moderate','Two gabapentinoids — additive sedation.'),
('gabapentin','tizanidine','moderate','Additive CNS sedation.'),
('gabapentin','tramadol','major','Opioid + gabapentinoid — respiratory depression / sedation.'),
('gemfibrozil','rosuvastatin','major','Statin + gemfibrozil — high rhabdomyolysis risk.'),
('gemfibrozil','simvastatin','major','Statin + gemfibrozil — high rhabdomyolysis risk.'),
('glibenclamide','ibuprofen','minor','NSAID may enhance sulfonylurea hypoglycemia.'),
('glibenclamide','indomethacin','minor','NSAID may enhance sulfonylurea hypoglycemia.'),
('glibenclamide','itraconazole','major','Azole raises sulfonylurea — hypoglycemia.'),
('glibenclamide','ketoconazole','major','Azole raises sulfonylurea — hypoglycemia.'),
('glibenclamide','ketorolac','minor','NSAID may enhance sulfonylurea hypoglycemia.'),
('glibenclamide','levofloxacin','moderate','Quinolone + sulfonylurea — dysglycemia.'),
('glibenclamide','mefenamic','minor','NSAID may enhance sulfonylurea hypoglycemia.'),
('glibenclamide','meloxicam','minor','NSAID may enhance sulfonylurea hypoglycemia.'),
('glibenclamide','methylprednisolone','moderate','Corticosteroid raises blood glucose — reduces antidiabetic effect.'),
('glibenclamide','metoprolol','moderate','Beta-blocker masks sulfonylurea hypoglycemia.'),
('glibenclamide','moxifloxacin','moderate','Quinolone + sulfonylurea — dysglycemia.'),
('glibenclamide','naproxen','minor','NSAID may enhance sulfonylurea hypoglycemia.'),
('glibenclamide','ofloxacin','moderate','Quinolone + sulfonylurea — dysglycemia.'),
('glibenclamide','piroxicam','minor','NSAID may enhance sulfonylurea hypoglycemia.'),
('glibenclamide','prednisolone','moderate','Corticosteroid raises blood glucose — reduces antidiabetic effect.'),
('glibenclamide','propranolol','moderate','Beta-blocker masks sulfonylurea hypoglycemia.'),
('gliclazide','ibuprofen','minor','NSAID may enhance sulfonylurea hypoglycemia.'),
('gliclazide','indomethacin','minor','NSAID may enhance sulfonylurea hypoglycemia.'),
('gliclazide','itraconazole','major','Azole raises sulfonylurea — hypoglycemia.'),
('gliclazide','ketoconazole','major','Azole raises sulfonylurea — hypoglycemia.'),
('gliclazide','ketorolac','minor','NSAID may enhance sulfonylurea hypoglycemia.'),
('gliclazide','levofloxacin','moderate','Quinolone + sulfonylurea — dysglycemia.'),
('gliclazide','mefenamic','minor','NSAID may enhance sulfonylurea hypoglycemia.'),
('gliclazide','meloxicam','minor','NSAID may enhance sulfonylurea hypoglycemia.'),
('gliclazide','methylprednisolone','moderate','Corticosteroid raises blood glucose — reduces antidiabetic effect.'),
('gliclazide','metoprolol','moderate','Beta-blocker masks sulfonylurea hypoglycemia.'),
('gliclazide','moxifloxacin','moderate','Quinolone + sulfonylurea — dysglycemia.'),
('gliclazide','naproxen','minor','NSAID may enhance sulfonylurea hypoglycemia.'),
('gliclazide','ofloxacin','moderate','Quinolone + sulfonylurea — dysglycemia.'),
('gliclazide','piroxicam','minor','NSAID may enhance sulfonylurea hypoglycemia.'),
('gliclazide','prednisolone','moderate','Corticosteroid raises blood glucose — reduces antidiabetic effect.'),
('gliclazide','propranolol','moderate','Beta-blocker masks sulfonylurea hypoglycemia.'),
('glimepiride','ibuprofen','minor','NSAID may enhance sulfonylurea hypoglycemia.'),
('glimepiride','indomethacin','minor','NSAID may enhance sulfonylurea hypoglycemia.'),
('glimepiride','itraconazole','major','Azole raises sulfonylurea — hypoglycemia.'),
('glimepiride','ketoconazole','major','Azole raises sulfonylurea — hypoglycemia.'),
('glimepiride','ketorolac','minor','NSAID may enhance sulfonylurea hypoglycemia.'),
('glimepiride','levofloxacin','moderate','Quinolone + sulfonylurea — dysglycemia.'),
('glimepiride','mefenamic','minor','NSAID may enhance sulfonylurea hypoglycemia.'),
('glimepiride','meloxicam','minor','NSAID may enhance sulfonylurea hypoglycemia.'),
('glimepiride','methylprednisolone','moderate','Corticosteroid raises blood glucose — reduces antidiabetic effect.'),
('glimepiride','metoprolol','moderate','Beta-blocker masks sulfonylurea hypoglycemia.'),
('glimepiride','moxifloxacin','moderate','Quinolone + sulfonylurea — dysglycemia.'),
('glimepiride','naproxen','minor','NSAID may enhance sulfonylurea hypoglycemia.'),
('glimepiride','ofloxacin','moderate','Quinolone + sulfonylurea — dysglycemia.'),
('glimepiride','piroxicam','minor','NSAID may enhance sulfonylurea hypoglycemia.'),
('glimepiride','prednisolone','moderate','Corticosteroid raises blood glucose — reduces antidiabetic effect.'),
('glimepiride','propranolol','moderate','Beta-blocker masks sulfonylurea hypoglycemia.'),
('glyceryl trinitrate','sildenafil','contraindicated','PDE5 inhibitor + nitrate — severe hypotension; never combine.'),
('glyceryl trinitrate','tadalafil','contraindicated','PDE5 inhibitor + nitrate — severe hypotension; never combine.'),
('glyceryl trinitrate','vardenafil','contraindicated','PDE5 inhibitor + nitrate — severe hypotension; never combine.'),
('haloperidol','moxifloxacin','major','Additive QT prolongation — torsades de pointes risk.'),
('haloperidol','ondansetron','major','Additive QT prolongation — torsades de pointes risk.'),
('heparin','ibuprofen','major','NSAID + anticoagulant — markedly increased bleeding risk.'),
('heparin','indomethacin','major','NSAID + anticoagulant — markedly increased bleeding risk.'),
('heparin','ketorolac','contraindicated','Ketorolac + anticoagulant — high GI/bleeding risk; avoid.'),
('heparin','mefenamic','major','NSAID + anticoagulant — markedly increased bleeding risk.'),
('heparin','meloxicam','major','NSAID + anticoagulant — markedly increased bleeding risk.'),
('heparin','naproxen','major','NSAID + anticoagulant — markedly increased bleeding risk.'),
('heparin','paroxetine','moderate','SSRI/SNRI + anticoagulant — increased bleeding risk.'),
('heparin','piroxicam','major','NSAID + anticoagulant — markedly increased bleeding risk.'),
('heparin','sertraline','moderate','SSRI/SNRI + anticoagulant — increased bleeding risk.'),
('heparin','venlafaxine','moderate','SSRI/SNRI + anticoagulant — increased bleeding risk.'),
('hydrochlorothiazide','ibuprofen','moderate','NSAID reduces diuretic effect; renal risk.'),
('hydrochlorothiazide','indomethacin','moderate','NSAID reduces diuretic effect; renal risk.'),
('hydrochlorothiazide','ketorolac','moderate','NSAID reduces diuretic effect; renal risk.'),
('hydrochlorothiazide','lithium','major','Thiazide/loop diuretic raises lithium levels — toxicity.'),
('hydrochlorothiazide','mefenamic','moderate','NSAID reduces diuretic effect; renal risk.'),
('hydrochlorothiazide','meloxicam','moderate','NSAID reduces diuretic effect; renal risk.'),
('hydrochlorothiazide','methylprednisolone','moderate','Corticosteroid + diuretic — additive hypokalemia.'),
('hydrochlorothiazide','naproxen','moderate','NSAID reduces diuretic effect; renal risk.'),
('hydrochlorothiazide','piroxicam','moderate','NSAID reduces diuretic effect; renal risk.'),
('hydrochlorothiazide','prednisolone','moderate','Corticosteroid + diuretic — additive hypokalemia.'),
('ibuprofen','indapamide','moderate','NSAID reduces diuretic effect; renal risk.'),
('ibuprofen','indomethacin','moderate','Two NSAIDs — additive GI ulcer / renal risk; avoid combining.'),
('ibuprofen','ketorolac','moderate','Two NSAIDs — additive GI ulcer / renal risk; avoid combining.'),
('ibuprofen','levofloxacin','minor','Quinolone + NSAID — slight seizure-threshold lowering.'),
('ibuprofen','lisinopril','moderate','NSAID reduces ACE/ARB effect and adds renal risk.'),
('ibuprofen','lithium','major','NSAID raises lithium levels — toxicity.'),
('ibuprofen','losartan','moderate','NSAID reduces ACE/ARB effect and adds renal risk.'),
('ibuprofen','mefenamic','moderate','Two NSAIDs — additive GI ulcer / renal risk; avoid combining.'),
('ibuprofen','meloxicam','moderate','Two NSAIDs — additive GI ulcer / renal risk; avoid combining.'),
('ibuprofen','methotrexate','major','NSAID raises methotrexate toxicity.'),
('ibuprofen','methylprednisolone','moderate','NSAID + corticosteroid — additive GI ulcer/bleeding risk.'),
('ibuprofen','moxifloxacin','minor','Quinolone + NSAID — slight seizure-threshold lowering.'),
('ibuprofen','naproxen','moderate','Two NSAIDs — additive GI ulcer / renal risk; avoid combining.'),
('ibuprofen','ofloxacin','minor','Quinolone + NSAID — slight seizure-threshold lowering.'),
('ibuprofen','piroxicam','moderate','Two NSAIDs — additive GI ulcer / renal risk; avoid combining.'),
('ibuprofen','prednisolone','moderate','NSAID + corticosteroid — additive GI ulcer/bleeding risk.'),
('ibuprofen','ramipril','moderate','NSAID reduces ACE/ARB effect and adds renal risk.'),
('ibuprofen','risedronate','moderate','NSAID + bisphosphonate — additive GI/esophageal irritation.'),
('ibuprofen','rivaroxaban','major','NSAID + anticoagulant — markedly increased bleeding risk.'),
('ibuprofen','spironolactone','moderate','NSAID + spironolactone — hyperkalemia / renal risk.'),
('ibuprofen','telmisartan','moderate','NSAID reduces ACE/ARB effect and adds renal risk.'),
('ibuprofen','valsartan','moderate','NSAID reduces ACE/ARB effect and adds renal risk.'),
('ibuprofen','warfarin','major','NSAID + anticoagulant — markedly increased bleeding risk.'),
('ibuprofen','zoledronic','moderate','NSAID + bisphosphonate — additive GI/esophageal irritation.'),
('indapamide','indomethacin','moderate','NSAID reduces diuretic effect; renal risk.'),
('indapamide','ketorolac','moderate','NSAID reduces diuretic effect; renal risk.'),
('indapamide','lithium','major','Thiazide/loop diuretic raises lithium levels — toxicity.'),
('indapamide','mefenamic','moderate','NSAID reduces diuretic effect; renal risk.'),
('indapamide','meloxicam','moderate','NSAID reduces diuretic effect; renal risk.'),
('indapamide','methylprednisolone','moderate','Corticosteroid + diuretic — additive hypokalemia.'),
('indapamide','naproxen','moderate','NSAID reduces diuretic effect; renal risk.'),
('indapamide','piroxicam','moderate','NSAID reduces diuretic effect; renal risk.'),
('indapamide','prednisolone','moderate','Corticosteroid + diuretic — additive hypokalemia.'),
('indomethacin','ketorolac','moderate','Two NSAIDs — additive GI ulcer / renal risk; avoid combining.'),
('indomethacin','levofloxacin','minor','Quinolone + NSAID — slight seizure-threshold lowering.'),
('indomethacin','lisinopril','moderate','NSAID reduces ACE/ARB effect and adds renal risk.'),
('indomethacin','lithium','major','NSAID raises lithium levels — toxicity.'),
('indomethacin','losartan','moderate','NSAID reduces ACE/ARB effect and adds renal risk.'),
('indomethacin','mefenamic','moderate','Two NSAIDs — additive GI ulcer / renal risk; avoid combining.'),
('indomethacin','meloxicam','moderate','Two NSAIDs — additive GI ulcer / renal risk; avoid combining.'),
('indomethacin','methotrexate','major','NSAID raises methotrexate toxicity.'),
('indomethacin','methylprednisolone','moderate','NSAID + corticosteroid — additive GI ulcer/bleeding risk.'),
('indomethacin','moxifloxacin','minor','Quinolone + NSAID — slight seizure-threshold lowering.'),
('indomethacin','naproxen','moderate','Two NSAIDs — additive GI ulcer / renal risk; avoid combining.'),
('indomethacin','ofloxacin','minor','Quinolone + NSAID — slight seizure-threshold lowering.'),
('indomethacin','piroxicam','moderate','Two NSAIDs — additive GI ulcer / renal risk; avoid combining.'),
('indomethacin','prednisolone','moderate','NSAID + corticosteroid — additive GI ulcer/bleeding risk.'),
('indomethacin','ramipril','moderate','NSAID reduces ACE/ARB effect and adds renal risk.'),
('indomethacin','risedronate','moderate','NSAID + bisphosphonate — additive GI/esophageal irritation.'),
('indomethacin','rivaroxaban','major','NSAID + anticoagulant — markedly increased bleeding risk.'),
('indomethacin','spironolactone','moderate','NSAID + spironolactone — hyperkalemia / renal risk.'),
('indomethacin','telmisartan','moderate','NSAID reduces ACE/ARB effect and adds renal risk.'),
('indomethacin','valsartan','moderate','NSAID reduces ACE/ARB effect and adds renal risk.'),
('indomethacin','warfarin','major','NSAID + anticoagulant — markedly increased bleeding risk.'),
('indomethacin','zoledronic','moderate','NSAID + bisphosphonate — additive GI/esophageal irritation.'),
('isosorbide','sildenafil','contraindicated','PDE5 inhibitor + nitrate — severe hypotension; never combine.'),
('isosorbide','tadalafil','contraindicated','PDE5 inhibitor + nitrate — severe hypotension; never combine.'),
('isosorbide','vardenafil','contraindicated','PDE5 inhibitor + nitrate — severe hypotension; never combine.'),
('itraconazole','phenytoin','major','Azole raises phenytoin — toxicity.'),
('itraconazole','rifampicin','moderate','Inducer lowers azole levels / azole raises inducer.'),
('itraconazole','rivaroxaban','major','Azole antifungal raises DOAC levels — bleeding risk.'),
('itraconazole','sildenafil','moderate','Raises PDE5-inhibitor levels — hypotension.'),
('itraconazole','simvastatin','major','Azole raises statin levels — myopathy risk.'),
('itraconazole','tadalafil','moderate','Raises PDE5-inhibitor levels — hypotension.'),
('itraconazole','vardenafil','moderate','Raises PDE5-inhibitor levels — hypotension.'),
('itraconazole','warfarin','major','Antibiotic potentiates warfarin — raised INR / bleeding.'),
('ketoconazole','phenytoin','major','Azole raises phenytoin — toxicity.'),
('ketoconazole','rifampicin','moderate','Inducer lowers azole levels / azole raises inducer.'),
('ketoconazole','rivaroxaban','major','Azole antifungal raises DOAC levels — bleeding risk.'),
('ketoconazole','sildenafil','moderate','Raises PDE5-inhibitor levels — hypotension.'),
('ketoconazole','simvastatin','major','Azole raises statin levels — myopathy risk.'),
('ketoconazole','tadalafil','moderate','Raises PDE5-inhibitor levels — hypotension.'),
('ketoconazole','vardenafil','moderate','Raises PDE5-inhibitor levels — hypotension.'),
('ketoconazole','warfarin','major','Antibiotic potentiates warfarin — raised INR / bleeding.'),
('ketorolac','levofloxacin','minor','Quinolone + NSAID — slight seizure-threshold lowering.'),
('ketorolac','lisinopril','moderate','NSAID reduces ACE/ARB effect and adds renal risk.'),
('ketorolac','lithium','major','NSAID raises lithium levels — toxicity.'),
('ketorolac','losartan','moderate','NSAID reduces ACE/ARB effect and adds renal risk.'),
('ketorolac','mefenamic','moderate','Two NSAIDs — additive GI ulcer / renal risk; avoid combining.'),
('ketorolac','meloxicam','moderate','Two NSAIDs — additive GI ulcer / renal risk; avoid combining.'),
('ketorolac','methotrexate','major','NSAID raises methotrexate toxicity.'),
('ketorolac','methylprednisolone','moderate','NSAID + corticosteroid — additive GI ulcer/bleeding risk.'),
('ketorolac','moxifloxacin','minor','Quinolone + NSAID — slight seizure-threshold lowering.'),
('ketorolac','naproxen','moderate','Two NSAIDs — additive GI ulcer / renal risk; avoid combining.'),
('ketorolac','ofloxacin','minor','Quinolone + NSAID — slight seizure-threshold lowering.'),
('ketorolac','piroxicam','moderate','Two NSAIDs — additive GI ulcer / renal risk; avoid combining.'),
('ketorolac','prednisolone','moderate','NSAID + corticosteroid — additive GI ulcer/bleeding risk.'),
('ketorolac','ramipril','moderate','NSAID reduces ACE/ARB effect and adds renal risk.'),
('ketorolac','risedronate','moderate','NSAID + bisphosphonate — additive GI/esophageal irritation.'),
('ketorolac','rivaroxaban','contraindicated','Ketorolac + anticoagulant — high GI/bleeding risk; avoid.'),
('ketorolac','spironolactone','moderate','NSAID + spironolactone — hyperkalemia / renal risk.'),
('ketorolac','telmisartan','moderate','NSAID reduces ACE/ARB effect and adds renal risk.'),
('ketorolac','valsartan','moderate','NSAID reduces ACE/ARB effect and adds renal risk.'),
('ketorolac','warfarin','contraindicated','Ketorolac + anticoagulant — high GI/bleeding risk; avoid.'),
('ketorolac','zoledronic','moderate','NSAID + bisphosphonate — additive GI/esophageal irritation.'),
('leflunomide','methotrexate','major','Methotrexate + leflunomide — hepatotoxicity / marrow suppression.'),
('levofloxacin','mefenamic','minor','Quinolone + NSAID — slight seizure-threshold lowering.'),
('levofloxacin','meloxicam','minor','Quinolone + NSAID — slight seizure-threshold lowering.'),
('levofloxacin','methylprednisolone','moderate','Corticosteroid + quinolone — tendon rupture risk.'),
('levofloxacin','naproxen','minor','Quinolone + NSAID — slight seizure-threshold lowering.'),
('levofloxacin','piroxicam','minor','Quinolone + NSAID — slight seizure-threshold lowering.'),
('levofloxacin','prednisolone','moderate','Corticosteroid + quinolone — tendon rupture risk.'),
('levofloxacin','sucralfate','moderate','Sucralfate reduces quinolone absorption — separate doses.'),
('levofloxacin','warfarin','major','Antibiotic potentiates warfarin — raised INR / bleeding.'),
('levothyroxine','omeprazole','moderate','PPI may reduce levothyroxine absorption.'),
('levothyroxine','pantoprazole','moderate','PPI may reduce levothyroxine absorption.'),
('levothyroxine','warfarin','moderate','Levothyroxine can raise INR with warfarin.'),
('linezolid','mirtazapine','major','Linezolid (MAOI) + serotonergic — serotonin syndrome risk.'),
('linezolid','naratriptan','major','Linezolid (MAOI) + serotonergic — serotonin syndrome risk.'),
('linezolid','paroxetine','major','Linezolid (MAOI) + serotonergic — serotonin syndrome risk.'),
('linezolid','sertraline','major','Linezolid (MAOI) + serotonergic — serotonin syndrome risk.'),
('linezolid','sumatriptan','major','Linezolid (MAOI) + serotonergic — serotonin syndrome risk.'),
('linezolid','tramadol','major','Linezolid (MAOI) + serotonergic — serotonin syndrome risk.'),
('linezolid','venlafaxine','major','Linezolid (MAOI) + serotonergic — serotonin syndrome risk.'),
('lisinopril','lithium','major','ACE/ARB raises lithium levels — toxicity.'),
('lisinopril','mefenamic','moderate','NSAID reduces ACE/ARB effect and adds renal risk.'),
('lisinopril','meloxicam','moderate','NSAID reduces ACE/ARB effect and adds renal risk.'),
('lisinopril','naproxen','moderate','NSAID reduces ACE/ARB effect and adds renal risk.'),
('lisinopril','piroxicam','moderate','NSAID reduces ACE/ARB effect and adds renal risk.'),
('lisinopril','potassium chloride','major','ACE/ARB + potassium — hyperkalemia.'),
('lisinopril','spironolactone','major','ACE/ARB + potassium-sparing diuretic — hyperkalemia.'),
('lisinopril','tizanidine','moderate','Tizanidine + antihypertensive — additive hypotension.'),
('lisinopril','trimethoprim','moderate','ACE/ARB + trimethoprim — hyperkalemia risk.'),
('lithium','losartan','major','ACE/ARB raises lithium levels — toxicity.'),
('lithium','mefenamic','major','NSAID raises lithium levels — toxicity.'),
('lithium','meloxicam','major','NSAID raises lithium levels — toxicity.'),
('lithium','metronidazole','moderate','Metronidazole may raise lithium levels.'),
('lithium','naproxen','major','NSAID raises lithium levels — toxicity.'),
('lithium','piroxicam','major','NSAID raises lithium levels — toxicity.'),
('lithium','ramipril','major','ACE/ARB raises lithium levels — toxicity.'),
('lithium','telmisartan','major','ACE/ARB raises lithium levels — toxicity.'),
('lithium','valsartan','major','ACE/ARB raises lithium levels — toxicity.'),
('losartan','mefenamic','moderate','NSAID reduces ACE/ARB effect and adds renal risk.'),
('losartan','meloxicam','moderate','NSAID reduces ACE/ARB effect and adds renal risk.'),
('losartan','naproxen','moderate','NSAID reduces ACE/ARB effect and adds renal risk.'),
('losartan','piroxicam','moderate','NSAID reduces ACE/ARB effect and adds renal risk.'),
('losartan','potassium chloride','major','ACE/ARB + potassium — hyperkalemia.'),
('losartan','spironolactone','major','ACE/ARB + potassium-sparing diuretic — hyperkalemia.'),
('losartan','tizanidine','moderate','Tizanidine + antihypertensive — additive hypotension.'),
('losartan','trimethoprim','moderate','ACE/ARB + trimethoprim — hyperkalemia risk.'),
('mefenamic','meloxicam','moderate','Two NSAIDs — additive GI ulcer / renal risk; avoid combining.'),
('mefenamic','methotrexate','major','NSAID raises methotrexate toxicity.'),
('mefenamic','methylprednisolone','moderate','NSAID + corticosteroid — additive GI ulcer/bleeding risk.'),
('mefenamic','moxifloxacin','minor','Quinolone + NSAID — slight seizure-threshold lowering.'),
('mefenamic','naproxen','moderate','Two NSAIDs — additive GI ulcer / renal risk; avoid combining.'),
('mefenamic','ofloxacin','minor','Quinolone + NSAID — slight seizure-threshold lowering.'),
('mefenamic','piroxicam','moderate','Two NSAIDs — additive GI ulcer / renal risk; avoid combining.'),
('mefenamic','prednisolone','moderate','NSAID + corticosteroid — additive GI ulcer/bleeding risk.'),
('mefenamic','ramipril','moderate','NSAID reduces ACE/ARB effect and adds renal risk.'),
('mefenamic','risedronate','moderate','NSAID + bisphosphonate — additive GI/esophageal irritation.'),
('mefenamic','rivaroxaban','major','NSAID + anticoagulant — markedly increased bleeding risk.'),
('mefenamic','spironolactone','moderate','NSAID + spironolactone — hyperkalemia / renal risk.'),
('mefenamic','telmisartan','moderate','NSAID reduces ACE/ARB effect and adds renal risk.'),
('mefenamic','valsartan','moderate','NSAID reduces ACE/ARB effect and adds renal risk.'),
('mefenamic','warfarin','major','NSAID + anticoagulant — markedly increased bleeding risk.'),
('mefenamic','zoledronic','moderate','NSAID + bisphosphonate — additive GI/esophageal irritation.'),
('meloxicam','methotrexate','major','NSAID raises methotrexate toxicity.'),
('meloxicam','methylprednisolone','moderate','NSAID + corticosteroid — additive GI ulcer/bleeding risk.'),
('meloxicam','moxifloxacin','minor','Quinolone + NSAID — slight seizure-threshold lowering.'),
('meloxicam','naproxen','moderate','Two NSAIDs — additive GI ulcer / renal risk; avoid combining.'),
('meloxicam','ofloxacin','minor','Quinolone + NSAID — slight seizure-threshold lowering.'),
('meloxicam','piroxicam','moderate','Two NSAIDs — additive GI ulcer / renal risk; avoid combining.'),
('meloxicam','prednisolone','moderate','NSAID + corticosteroid — additive GI ulcer/bleeding risk.'),
('meloxicam','ramipril','moderate','NSAID reduces ACE/ARB effect and adds renal risk.'),
('meloxicam','risedronate','moderate','NSAID + bisphosphonate — additive GI/esophageal irritation.'),
('meloxicam','rivaroxaban','major','NSAID + anticoagulant — markedly increased bleeding risk.'),
('meloxicam','spironolactone','moderate','NSAID + spironolactone — hyperkalemia / renal risk.'),
('meloxicam','telmisartan','moderate','NSAID reduces ACE/ARB effect and adds renal risk.'),
('meloxicam','valsartan','moderate','NSAID reduces ACE/ARB effect and adds renal risk.'),
('meloxicam','warfarin','major','NSAID + anticoagulant — markedly increased bleeding risk.'),
('meloxicam','zoledronic','moderate','NSAID + bisphosphonate — additive GI/esophageal irritation.'),
('methotrexate','naproxen','major','NSAID raises methotrexate toxicity.'),
('methotrexate','omeprazole','moderate','PPI may raise methotrexate levels.'),
('methotrexate','pantoprazole','moderate','PPI may raise methotrexate levels.'),
('methotrexate','piroxicam','major','NSAID raises methotrexate toxicity.'),
('methotrexate','sulfamethoxazole','major','Antifolate + methotrexate — marrow suppression.'),
('methotrexate','trimethoprim','major','Antifolate + methotrexate — marrow suppression.'),
('methylprednisolone','moxifloxacin','moderate','Corticosteroid + quinolone — tendon rupture risk.'),
('methylprednisolone','naproxen','moderate','NSAID + corticosteroid — additive GI ulcer/bleeding risk.'),
('methylprednisolone','ofloxacin','moderate','Corticosteroid + quinolone — tendon rupture risk.'),
('methylprednisolone','phenytoin','moderate','Enzyme inducer lowers corticosteroid effect.'),
('methylprednisolone','piroxicam','moderate','NSAID + corticosteroid — additive GI ulcer/bleeding risk.'),
('methylprednisolone','rifampicin','moderate','Enzyme inducer lowers corticosteroid effect.'),
('methylprednisolone','warfarin','moderate','Corticosteroid can alter INR with warfarin.'),
('metoprolol','timolol','moderate','Topical + systemic beta-blocker — additive bradycardia.'),
('metoprolol','verapamil','major','Beta-blocker + verapamil/diltiazem — bradycardia / AV block.'),
('metronidazole','warfarin','major','Antibiotic potentiates warfarin — raised INR / bleeding.'),
('moxifloxacin','naproxen','minor','Quinolone + NSAID — slight seizure-threshold lowering.'),
('moxifloxacin','ondansetron','major','Additive QT prolongation — torsades de pointes risk.'),
('moxifloxacin','piroxicam','minor','Quinolone + NSAID — slight seizure-threshold lowering.'),
('moxifloxacin','prednisolone','moderate','Corticosteroid + quinolone — tendon rupture risk.'),
('moxifloxacin','sucralfate','moderate','Sucralfate reduces quinolone absorption — separate doses.'),
('moxifloxacin','warfarin','major','Antibiotic potentiates warfarin — raised INR / bleeding.'),
('naproxen','ofloxacin','minor','Quinolone + NSAID — slight seizure-threshold lowering.'),
('naproxen','piroxicam','moderate','Two NSAIDs — additive GI ulcer / renal risk; avoid combining.'),
('naproxen','prednisolone','moderate','NSAID + corticosteroid — additive GI ulcer/bleeding risk.'),
('naproxen','ramipril','moderate','NSAID reduces ACE/ARB effect and adds renal risk.'),
('naproxen','risedronate','moderate','NSAID + bisphosphonate — additive GI/esophageal irritation.'),
('naproxen','rivaroxaban','major','NSAID + anticoagulant — markedly increased bleeding risk.'),
('naproxen','spironolactone','moderate','NSAID + spironolactone — hyperkalemia / renal risk.'),
('naproxen','telmisartan','moderate','NSAID reduces ACE/ARB effect and adds renal risk.'),
('naproxen','valsartan','moderate','NSAID reduces ACE/ARB effect and adds renal risk.'),
('naproxen','warfarin','major','NSAID + anticoagulant — markedly increased bleeding risk.'),
('naproxen','zoledronic','moderate','NSAID + bisphosphonate — additive GI/esophageal irritation.'),
('naratriptan','paroxetine','moderate','Triptan + SSRI/SNRI — serotonin syndrome risk.'),
('naratriptan','sertraline','moderate','Triptan + SSRI/SNRI — serotonin syndrome risk.'),
('naratriptan','venlafaxine','moderate','Triptan + SSRI/SNRI — serotonin syndrome risk.'),
('nitroglycerin','sildenafil','contraindicated','PDE5 inhibitor + nitrate — severe hypotension; never combine.'),
('nitroglycerin','tadalafil','contraindicated','PDE5 inhibitor + nitrate — severe hypotension; never combine.'),
('nitroglycerin','vardenafil','contraindicated','PDE5 inhibitor + nitrate — severe hypotension; never combine.'),
('ofloxacin','piroxicam','minor','Quinolone + NSAID — slight seizure-threshold lowering.'),
('ofloxacin','prednisolone','moderate','Corticosteroid + quinolone — tendon rupture risk.'),
('ofloxacin','sucralfate','moderate','Sucralfate reduces quinolone absorption — separate doses.'),
('paracetamol','warfarin','minor','Regular high-dose paracetamol may raise INR.'),
('paroxetine','rivaroxaban','moderate','SSRI/SNRI + anticoagulant — increased bleeding risk.'),
('paroxetine','sumatriptan','moderate','Triptan + SSRI/SNRI — serotonin syndrome risk.'),
('paroxetine','tramadol','major','Tramadol + SSRI/SNRI — serotonin syndrome and seizure risk.'),
('paroxetine','warfarin','moderate','SSRI/SNRI + anticoagulant — increased bleeding risk.'),
('phenytoin','prednisolone','moderate','Enzyme inducer lowers corticosteroid effect.'),
('phenytoin','rivaroxaban','major','Enzyme inducer lowers DOAC levels — clot risk.'),
('phenytoin','simvastatin','moderate','Enzyme inducer lowers statin levels.'),
('piroxicam','prednisolone','moderate','NSAID + corticosteroid — additive GI ulcer/bleeding risk.'),
('piroxicam','ramipril','moderate','NSAID reduces ACE/ARB effect and adds renal risk.'),
('piroxicam','risedronate','moderate','NSAID + bisphosphonate — additive GI/esophageal irritation.'),
('piroxicam','rivaroxaban','major','NSAID + anticoagulant — markedly increased bleeding risk.'),
('piroxicam','spironolactone','moderate','NSAID + spironolactone — hyperkalemia / renal risk.'),
('piroxicam','telmisartan','moderate','NSAID reduces ACE/ARB effect and adds renal risk.'),
('piroxicam','valsartan','moderate','NSAID reduces ACE/ARB effect and adds renal risk.'),
('piroxicam','warfarin','major','NSAID + anticoagulant — markedly increased bleeding risk.'),
('piroxicam','zoledronic','moderate','NSAID + bisphosphonate — additive GI/esophageal irritation.'),
('potassium chloride','ramipril','major','ACE/ARB + potassium — hyperkalemia.'),
('potassium chloride','spironolactone','major','Potassium-sparing diuretic + potassium — hyperkalemia.'),
('potassium chloride','telmisartan','major','ACE/ARB + potassium — hyperkalemia.'),
('potassium chloride','valsartan','major','ACE/ARB + potassium — hyperkalemia.'),
('prednisolone','rifampicin','moderate','Enzyme inducer lowers corticosteroid effect.'),
('prednisolone','warfarin','moderate','Corticosteroid can alter INR with warfarin.'),
('pregabalin','tizanidine','moderate','Additive CNS sedation.'),
('pregabalin','tramadol','major','Opioid + gabapentinoid — respiratory depression / sedation.'),
('propranolol','timolol','moderate','Topical + systemic beta-blocker — additive bradycardia.'),
('propranolol','verapamil','major','Beta-blocker + verapamil/diltiazem — bradycardia / AV block.'),
('ramipril','spironolactone','major','ACE/ARB + potassium-sparing diuretic — hyperkalemia.'),
('ramipril','tizanidine','moderate','Tizanidine + antihypertensive — additive hypotension.'),
('ramipril','trimethoprim','moderate','ACE/ARB + trimethoprim — hyperkalemia risk.'),
('rifampicin','rivaroxaban','major','Enzyme inducer lowers DOAC levels — clot risk.'),
('rifampicin','simvastatin','moderate','Enzyme inducer lowers statin levels.'),
('rivaroxaban','sertraline','moderate','SSRI/SNRI + anticoagulant — increased bleeding risk.'),
('rivaroxaban','venlafaxine','moderate','SSRI/SNRI + anticoagulant — increased bleeding risk.'),
('rosuvastatin','warfarin','minor','Statin may modestly raise INR with warfarin.'),
('sertraline','sumatriptan','moderate','Triptan + SSRI/SNRI — serotonin syndrome risk.'),
('sertraline','tramadol','major','Tramadol + SSRI/SNRI — serotonin syndrome and seizure risk.'),
('sertraline','warfarin','moderate','SSRI/SNRI + anticoagulant — increased bleeding risk.'),
('simvastatin','verapamil','moderate','Verapamil/diltiazem raises statin levels — myopathy.'),
('simvastatin','warfarin','minor','Statin may modestly raise INR with warfarin.'),
('spironolactone','telmisartan','major','ACE/ARB + potassium-sparing diuretic — hyperkalemia.'),
('spironolactone','valsartan','major','ACE/ARB + potassium-sparing diuretic — hyperkalemia.'),
('sulfamethoxazole','warfarin','major','Antibiotic potentiates warfarin — raised INR / bleeding.'),
('sumatriptan','venlafaxine','moderate','Triptan + SSRI/SNRI — serotonin syndrome risk.'),
('telmisartan','tizanidine','moderate','Tizanidine + antihypertensive — additive hypotension.'),
('telmisartan','trimethoprim','moderate','ACE/ARB + trimethoprim — hyperkalemia risk.'),
('timolol','verapamil','moderate','Topical beta-blocker + verapamil/diltiazem — bradycardia.'),
('tizanidine','tramadol','major','Opioid + muscle relaxant — CNS/respiratory depression.'),
('tizanidine','valsartan','moderate','Tizanidine + antihypertensive — additive hypotension.'),
('tramadol','venlafaxine','major','Tramadol + SSRI/SNRI — serotonin syndrome and seizure risk.'),
('tramadol','warfarin','moderate','Tramadol may raise INR with warfarin.'),
('trimethoprim','valsartan','moderate','ACE/ARB + trimethoprim — hyperkalemia risk.'),
('trimethoprim','warfarin','major','Antibiotic potentiates warfarin — raised INR / bleeding.'),
('venlafaxine','warfarin','moderate','SSRI/SNRI + anticoagulant — increased bleeding risk.');
